[project]
name = "common-sense-big-o"
version = "0.1.0"
authors = [
    { name = "Matt Winfield", email = "matthew.r.winfield@faa.gov" }
]

requires-python = ">=3.14,<3.15"

dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.0",
    "python-decouple>=3.8",
]
